# -*- coding: utf-8 -*-
"""
@file      :  cutTimeDict.py
@Time      :  2022/9/29 09:59
@Software  :  PyCharm
@summary   :
@Author    :  Bajian Xiang
"""

rir_dict = {'BatteryQuarles_left': 1, 'yikehuichashi01_right': 9, 'BatteryQuarles_right': 1,
            'yikehuilaobanshi01_right': 0,
            'yikehuilaobanshi02_left': 8, 'xiaohedaban-01_right': 14, 'yikehuilaobanshi01_left': 26,
            'BatteryBenson_left': 0,
            'yikehuihuiyishi02_left': 2, 'junzheng5ktv01_right': 0, 'PortageCreekTunnel_left': 0,
            'yiteng701dabangong01_left': 1,
            'yikehuilaobanshi02_right': 34, 'junzheng5ktv01_left': 14, 'yiteng701dabangong01_right': 2,
            'junzheng5ktv02_left': 17,
            'xiaohedaban-01_left': 0, 'junzheng5ktv02_right': 5, 'CCRMAStairwell_right': 8,
            'SewardWaterfrontPark_right': 0,
            'SewardWaterfrontPark_left': 1, 'BatteryBrannan_left': 2, 'CCRMAStairwell_left': 2,
            'RacquetballCourt_left': 1,
            '3000CStreetGarageStairwell_left': 8, 'BatteryBrannan_right': 0, 'NancyLakeTunnel_right': 0,
            'CedarCreekWinery_left': 0,
            'TonyKnowlesCoastalTrailTunnel_right': 1, 'SquareVictoriaDome_left': 26, 'RacquetballCourt_right': 3,
            '3000CStreetGarageStairwell_right': 0, 'NancyLakeTunnel_left': 2, 'GraffitiHallway_right': 4,
            'GraffitiHallway_left': 3,
            'TonyKnowlesCoastalTrailTunnel_left': 1, 'BatteryRandol_right': 1, 'StrathconaStairwellMcGill_right': 2,
            'BatteryBenson_right': 1, 'PortageCreekTunnel_right': 0, 'HaleHolisticYogaStudio_right': 1,
            'PabellonCulturalDeLaRepublica_left': 1, 'TransitCenter_left': 0, 'OutbackClimbingCenter_left': 1,
            'HaleHolisticYogaStudio_left': 1, 'WaterplacePark_left': 1, 'BatteryRandol_left': 1, 'Natatorium_left': 0,
            'LittlefieldLobby_left': 0, 'StrathconaStairwellMcGill_left': 0, 'OutbackClimbingCenter_right': 0,
            'PabellonCulturalDeLaRepublica_right': 1, 'WaterplacePark_right': 0, 'TransitCenter_right': 0,
            'ByronGlacier_left': 0,
            'FatMansMisery_right': 0, 'CliffOfTheDawn_left': 1, 'QuadracciPavilion_right': 0, 'Amaranth_left': 0,
            'FatMansMisery_left': 13,
            'Amaranth_right': 0, 'ByronGlacier_right': 1, 'BatteryTolles_left': 1, 'FishCreekTrestleBridge_right': 0,
            'FatMansSqueeze_right': 2, 'PabstBrewery_left': 1, 'ConvocationMall_left': 0, 'CliffOfTheDawn_right': 1,
            'FishCreekTrestleBridge_left': 13, 'PabstBrewery_right': 1, 'ConvocationMall_right': 0,
            'QuadracciPavilion_left': 1,
            'junzheng3dahui02_left': 0, 'junzheng3dahui03_right': 0, 'junzheng304hui02_right': 6,
            'xiaohedaban-03_left': 1,
            'xiaohedaban-03_right': 11, 'junzheng5chashi01_left': 0, 'junzheng310hui02_right': 4,
            'junzheng3dahui02_right': 0,
            'yiteng701dabangong02_right': 35, 'junzheng304hui01_right': 3, 'xiaohedaban-02_left': 2,
            'junzheng5chashi01_right': 10,
            'junzheng310hui02_left': 5, 'junzheng310hui01_right': 1, 'junzheng3dahui03_left': 9,
            'xiaohedaban-02_right': 3,
            'junzheng3dahui01_left': 26, 'junzheng304hui01_left': 6, 'BatteryPowell_right': 0,
            'PurgatoryChasm_right': 1,
            'StorageTankNo7_right': 1, 'Avenue52UnderpassLARiver_left': 0, 'BoulevardRosemontUnderpass_right': 1,
            'TheSlot_left': 0,
            'WangenheimRareBooksRoom_left': 0, 'TheSlot_right': 0, 'LawrenceWelkCave_left': 28,
            'WangenheimRareBooksRoom_right': 0,
            'StorageTankNo7_left': 0, 'MillsGreekTheater_right': 0, 'LakeMerrittBART_right': 0,
            'MillsGreekTheater_left': 2,
            'LakeMerrittBART_left': 0, 'LawrenceWelkCave_right': 7, 'BoulevardRosemontUnderpass_left': 1,
            'BatteryPowell_left': 0}